### ISSUE TITLE
On mobile, rotation by flicking is accidental & annoying

### ISSUE THREAD

**Issue by ittayd** [wrandelshofer/VirtualCube#2]
On a mobile phone it is easy to intend to rotate a face, but accidently have a gesture that is interpreted as a flick causing the cube to rotate wildly. It would be better if there are keys (e.g. curved arrows in the corners of the canvas) that cause rotation while touch&drag can only mean face rotation. 
Even better, have touch&drag only mean the 'x' or 'y' or 'z' moves (and work with the speed of normal face rotation). That way algorithms that use these can be executed more or less intuitively.

**Comment by wrandelshofer** [comment]
This is a very good suggestion. 

I am currently working on the 3d model for the 4x4 cube, and I will add 5x5, 6x6, 7x7 cube models later. These cubes have more mid-layers which will make this problem even more acute.

I am pondering whether it would be enough to just separate the two functions spatially. That is, without adding buttons.

E.g.
- touch&drag on the cube is interpreted as a twist
- touch&drag that starts at half a finger distance or more from the cube is interpreted as a rotation of the cube 

Or maybe it is better to forget about touch&drag for twisting at all, and only do a twist on a touch on a sticker of the cube. 

e.g.
- touch a sticker on a corner or on a center piece to rotate a face
- touch a sticker on an edge piece to rotate a mid-layer

Maybe I should do some prototyping with various ideas, and put them online, so that various people can try them out?

**Comment by ittayd** [comment]
You can also have a hot zone on one of the corners where dragging there is rotation.
Alternatively, maybe having a button to reset the orientation will be good for the ocasional miss.

**Comment by wrandelshofer** [comment]
I finally made a fix for this issue. It is fixed with commit 16b90ff3.

- Rotating the cube now only works when the mouse drag starts in the corner region.
- A single click on the reset button now only resets the orientation of the cube.
- A double click on the reset button is now required to fully reset the cube.
