### ISSUE TITLE
Consider using pegjs for parsing

### ISSUE THREAD

**Issue by ittayd** [wrandelshofer/VirtualCube#3]
Parser generators are easier to understand and maintain.

**Comment by wrandelshofer** [comment]
I briefly considered using a parser generator, but then decided against it, because this particular parser is configurable. 

We can change many aspects of the input language:
- enable/disable various language constructs, 
- select a syntax for various language constructs,
- define terminal symbols of the language

Maybe I have not done enough research, but I thought that is not a typical use case for parser generators.

The code in ScriptParser.mjs is translated from ScriptParser.java from the CubeTwister project. I have not copied all comments from the Java version over to the JavaScript version. That makes the JavaScript version harder to understand.

**Comment by ittayd** [comment]
The pegjs file can be generated dynamically, on the client side.

**Comment by wrandelshofer** [comment]
This is not a good solution. 

This won't improve understandabillity and maintanability of the code, because now instead of  just having to implement a parser, I would have to implement a code generator for the grammar syntax, and to write the plumbing for running that grammar syntax through the parser generator. 

Then I would have to either port a parser generator from JavaScript to Java or the other way round, because there is none available for both platforms.

The ScriptParser.mjs is just one third the size of parser.js in PEG.js (and this is not the only file needed from PEG.js to make it work). So the resulting code will definitely be larger than the code I have now.

**Comment by ittayd** [comment]
I thought generation would be just removing / adding tokens from a file that contains the fullest dictionary. So more like find&replace than actual generation. 
I'm using pegjs with just peg.js.

And not sure this is all required for the client side javascript, unless you intent is to turn this to the full fledge twister program. I think now days there is pretty standard notation that everyone is using (in particular sites like algdb.net), so not sure if the need for dynamically created notation is really needed.

**Comment by wrandelshofer** [comment]
My goal is to use VirtualCube as a drop-in replacement for my RubikPlayer Java applets, including support for several script languages. So, I refactored the existing parser I had in those applets (which is the same as in CubeTwister) to improve its portability to JavaScript, and then ported it. My idea is to keep them both in sync in the future.

I personally want to have support for multiple notations in JavaScript, because this allows to build a client-based web-tool that can translate between notations.


I am pondering now whether VirtualCube is modular enough, so that its parser module could be easily replaced by a different one, if desired.

I think it boils down to:
- A factory for a new parser instance, that takes a notation and a list of local macros as input.
- A method on the parser instance that takes a string as input and returns an AST from the ScriptAST module or throws an exception.

Do you need support for the notation used by algdb.net?
There are several ways how this notation can be supported by VirtualCube:
a.1) Add the notation to notations.xml, so that it can be selected using the "notation" parameter.
a.2) Create a new notations.xml file and select it using the "resourceFile" parameter.
b) Implement a module with a hard-coded notation, like class DefaultNotation in module ScriptNotation.
c) Replace the ScriptParser module by a different implementation that contains a parser that can parse the notation used by algdb.net. This parser could have been generated using peg.js.

I can do a.1)/a.2) for you, and add a test page that tests if it works.
I can do b) for you as well, if you need it.
I can support you with c) - I have no experience with peg.js though.

Is the notation used by algdb.net defined somewhere?

**Comment by ittayd** [comment]
I didn't mean to suggest that algdb notation is not used. Just to say that I think nowdays sites like algdb have made just one notation being used. At least in my perspective, I didn't see any other notation other than U/u/U'/U2 and the like being used (maybe in some ancient academic papers). Is it worth having support for arcane notations in the core instead of supporting the mainstream one only?

One can always create a tools that translates one notation onto another. 

The idea of a parser factory seems good. That way each parser can be defined succinctly, and people may just grab the parser of the notation they like, thereby getting just that amount of code.

**Comment by wrandelshofer** [comment]
This parser is precisely designed so that it can be used as a translation tool between notations. This is why the notation class is separate from the parser class in the code.

Well, for me, it is worth to have support for an arcane notation, because my web-site uses such a notation.😂
It has features that only very few notations have, so I can not switch to most other notations.

So, looking at ScriptParser.mjs. It currently exports 3 objects:
- A class for parse exceptions
- A class for parsing scripts
- A function to create random scripts

So, clearly, the function for creating random scripts does not belong here. 
I think, ParseException does not need to be exported at all.

Is it a workable solution for you, if do the following:
- I describe the interface for the exported class ScriptParser in ScriptParser.mjs. 
- I remove the function for random scripts and the export of ParseException

You will then be able to replace ScriptParser.mjs with a module of your choice - all it has to do, is to export a ScriptParser class that can parse a String into an AST defined in ScriptAST.mjs.

**Comment by wrandelshofer** [comment]
I have now changed the module ScriptParser.mjs so that it only exports a single class now.
The API of the class is defined in ScriptParserInterface. So, you should now be able to easily replace this module with a different one.

The changes are in: ad8ff6c44ba1e0a290811abe3dd0d80f3373c3f5
